PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.org/>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX opengis: <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX xmls: <http://www.w3.org/2001/XMLSchema#>
PREFIX strdf: <http://strdf.di.uoa.gr/ontology#>
SELECT * {
  ?p rdf:type ex:square .
  ?q rdf:type ex:square .
  ?p ex:color ?color3 .
  ?q ex:color ?color3 .
  ?p geosparql:asWKT ?sq1 .
  ?q geosparql:asWKT ?sq2 .
}