apiVersion: kobedataset.kobe.com/v1alpha1
kind: KobeDataset
metadata:
  name: pt-strabon
spec:
  image: antru6/strabon
  env:
  - name: STRABON_CONNECTION_hostname
    value: "pt-postgis"
  - name: STRABON_CONNECTION_port
    value: "5432"
  downloadFrom: http://users.iit.demokritos.gr/~antru/dumps/points.tar.gz
  forceLoad: true
  sparqlEnding: /strabon/Query
  count: 1
  port: 8080
