apiVersion: kobedataset.kobe.com/v1alpha1
kind: KobeDataset
metadata:
  name: sq-strabon
spec:
  image: antru6/strabon
  env:
  - name: STRABON_CONNECTION_hostname
    value: "sq-postgis"
  - name: STRABON_CONNECTION_port
    value: "5432"
  downloadFrom: http://users.iit.demokritos.gr/~antru/dumps/squares.tar.gz
  forceLoad: true
  sparqlEnding: /strabon/Query
  count: 1
  port: 8080
