apiVersion: kobedataset.kobe.com/v1alpha1
kind: KobeDataset
metadata:
  name: tmp-strabon
spec:
  image: antru6/gsgbl-strabon
  env:
  - name: STRABON_CONNECTION_hostname
    value: "tmp-postgis"
  - name: STRABON_CONNECTION_port
    value: "5432"
  - name: PTCL_QUERY
    value: "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX ex: <http://example.org/>
      PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
      PREFIX opengis: <http://www.opengis.net/def/uom/OGC/1.0/>
      PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
      PREFIX xmls: <http://www.w3.org/2001/XMLSchema#>
      PREFIX strdf: <http://strdf.di.uoa.gr/ontology#>
      SELECT * {
        ?x rdf:type ex:point .
        ?y rdf:type ex:point .
        ?x ex:color ?color1 .
        ?y ex:color ?color2 .
        ?x geosparql:asWKT ?pt1 .
        ?y geosparql:asWKT ?pt2 .
        FILTER (str(?color1) != str(?color2))
        FILTER (geof:distance(?pt1, ?pt2, opengis:metre) < '1000000.0'^^xmls:double)
      }"
  - name: SQCL_QUERY
    value: "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX ex: <http://example.org/>
      PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
      PREFIX opengis: <http://www.opengis.net/def/uom/OGC/1.0/>
      PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
      PREFIX xmls: <http://www.w3.org/2001/XMLSchema#>
      PREFIX strdf: <http://strdf.di.uoa.gr/ontology#>
      SELECT * {
        ?p rdf:type ex:square .
        ?q rdf:type ex:square .
        ?p ex:color ?color3 .
        ?q ex:color ?color3 .
        ?p geosparql:asWKT ?sq1 .
        ?q geosparql:asWKT ?sq2 .
      }"
  forceLoad: true
  sparqlEnding: /strabon/Query
  count: 1
  port: 8080
